CREATE PROCEDURE [dbo].[getList4ILS]

AS
	select RTRIM(FAMILIYA) AS FAMILIYA, RTRIM(IMYA) AS IMYA, RTRIM(OTCHECTVO) AS OTCHECTVO, convert(date, DATA_ROZD, 104) AS DATA_ROZD, KEY_1
	FROM AAQQ WHERE FAMILIYA <> '' and LICH_NOM_2 <> 'совмещ' and GRUP <> 2473
	ORDER BY FAMILIYA, IMYA, OTCHECTVO
RETURN 0
